#/bin/sh

WORKSPACE_ID=$1
URL=$(jq -Rs '{"description": "Auto-generated by Coder", "public": false, "files": {"'$WORKSPACE_ID.sh'": {"content": .}}}' /tmp/$WORKSPACE_ID.sh | curl -s -H "Authorization: bearer $GITHUB_TOKEN" -X POST -d @- "https://api.github.com/gists" | jq -r .files[\"$WORKSPACE_ID.sh\"].raw_url)
jq -n --arg url "$URL" '{"url":$url}'
